<?php
/*
*file:xhclass file
*time:2015-04-07 21:21:19
*/

return array(
	26=>array('name'=>'原创笑话',
			'type'=>'1',
			'nums'=>'184',
			'miaoshu'=>'原创笑话,精华笑话,网站里的网友发表的笑话，yuanchuang的笑话'
			),
	20=>array('name'=>'愚人笑话',
			'type'=>'1',
			'nums'=>'1297',
			'miaoshu'=>'愚人笑话,愚人搞笑,愚人,傻子搞笑,傻子搞笑,yurenxiaohua,yurengaoxiao,shazigaoxiao'
			),
	6=>array('name'=>'家庭笑话',
			'type'=>'1',
			'nums'=>'1071',
			'miaoshu'=>'家庭笑话,家人笑话,一家人笑话,家庭搞笑,jiarenxiaohua,jitinggaoxiao'
			),
	27=>array('name'=>'动物笑话',
			'type'=>'1',
			'nums'=>'211',
			'miaoshu'=>'动物笑话,和动物相关的搞笑的短文笑话，搞笑的动物笑话，笑死人的动物笑话.dongwuxiaohua,gaoxiaodedongwu'
			),
	25=>array('name'=>'英语笑话',
			'type'=>'1',
			'nums'=>'9',
			'miaoshu'=>'英语笑话,搞笑的英语段落,搞笑的英语文章,gaoxiaodeyingyuxiaohua,gaoxiangenglishpage'
			),
	22=>array('name'=>'笑话故事',
			'type'=>'1',
			'nums'=>'1309',
			'miaoshu'=>'笑话故事,综合笑话,各种各样的笑话,zonghexiaohua,gezhonggeyangdexianghua'
			),
	13=>array('name'=>'交通笑话',
			'type'=>'1',
			'nums'=>'1584',
			'miaoshu'=>'交通笑话,交通运输笑话,开车笑话,jiaotongxiaohua,kaichexiaohua'
			),
	16=>array('name'=>'鬼话笑话',
			'type'=>'1',
			'nums'=>'746',
			'miaoshu'=>'鬼话笑话,鬼话,关于鬼笑话,guihuaxiaohua,guihua'
			),
	24=>array('name'=>'幽默笑话',
			'type'=>'1',
			'nums'=>'440',
			'miaoshu'=>'幽默笑话,很幽默的笑话，很幽默的文章。youmoxiaohua,youmowenzhang'
			),
	18=>array('name'=>'名人笑话',
			'type'=>'1',
			'nums'=>'1617',
			'miaoshu'=>'名人笑话,名人,名人搞笑,有名的人笑话,mingrenxiaohua,mingren,mingrengaoxiao'
			),
	17=>array('name'=>'成人笑话',
			'type'=>'1',
			'nums'=>'2868',
			'miaoshu'=>'成人笑话,校园笑话,大学笑话,宿舍笑话,学生笑话,大学校园搞笑,xiaoyuanxiaohua,daxuexiaohua,sushexiaohua'
			),
	21=>array('name'=>'民间笑话',
			'type'=>'1',
			'nums'=>'1269',
			'miaoshu'=>'民间笑话,民间故事,民间搞笑,mingjianxiaohua,mingjiangushi,mingjiangaoxiao'
			),
	23=>array('name'=>'黄色笑话',
			'type'=>'1',
			'nums'=>'6242',
			'miaoshu'=>'黄色笑话,成人笑话,主要是一些成人相关的笑话,和成人相关的文章,chengrenxiaohua,chengrendewenzhang'
			),
	19=>array('name'=>'交往笑话',
			'type'=>'1',
			'nums'=>'1085',
			'miaoshu'=>'交往笑话,朋友交往笑话,情人交往笑话,交往搞笑,jiaowangxiaohua,pengyoujiaowang'
			),
	1=>array('name'=>'儿童笑话',
			'type'=>'1',
			'nums'=>'2564',
			'miaoshu'=>'儿童笑话,搞笑儿童笑话,儿童,笑话,ertong,ertongxiaohua'
			),
	15=>array('name'=>'文艺笑话',
			'type'=>'1',
			'nums'=>'693',
			'miaoshu'=>'文艺笑话,文艺,文艺搞笑,搞笑文艺短文,wenyixiaohua,wenyigaoxiao'
			),
	2=>array('name'=>'夫妻笑话',
			'type'=>'1',
			'nums'=>'2547',
			'miaoshu'=>'夫妻笑话,夫妻,夫妻搞笑对话,夫妻之间笑话,fuqixiaohua,fuqi,fuqigaoxiao'
			),
	3=>array('name'=>'古代笑话',
			'type'=>'1',
			'nums'=>'2518',
			'miaoshu'=>'古代笑话,古代,古代人的笑话,关于古代的笑话,gudaixiaohua,gudairenxiaohua'
			),
	4=>array('name'=>'爱情笑话',
			'type'=>'1',
			'nums'=>'1317',
			'miaoshu'=>'爱情笑话,情话,爱情搞笑,搞笑爱情,aiqingxiaohua,qinghua,gaoxiaoaiqing'
			),
	5=>array('name'=>'医疗笑话',
			'type'=>'1',
			'nums'=>'1236',
			'miaoshu'=>'医疗笑话,医院笑话,治病笑话,医生笑话,yiliaoxiaohua,yiyuanxiaohua'
			),
	7=>array('name'=>'政治笑话',
			'type'=>'1',
			'nums'=>'831',
			'miaoshu'=>'政治笑话,国家笑话,政治,国家政治笑话,zhengzhixiaohua,guojiaxiaohua'
			),
	8=>array('name'=>'电脑笑话',
			'type'=>'1',
			'nums'=>'1095',
			'miaoshu'=>'电脑笑话,电脑搞笑,搞笑电脑,diaonaoxiaohua,gaoxiaodiannao'
			),
	9=>array('name'=>'军事笑话',
			'type'=>'1',
			'nums'=>'1776',
			'miaoshu'=>'军事笑话,搞笑军队,军队里笑话,战争笑话,junshixiaohua,jinduixiaohua'
			),
	10=>array('name'=>'经营笑话',
			'type'=>'1',
			'nums'=>'1789',
			'miaoshu'=>'经营笑话,经营,jingyingxiaohua,jingying'
			),
	11=>array('name'=>'体育笑话',
			'type'=>'1',
			'nums'=>'539',
			'miaoshu'=>'体育笑话,体育,打球笑话,体育运动笑话,tiyuxiaohua,tiyuyudongxiaohua'
			),
	12=>array('name'=>'司法笑话',
			'type'=>'1',
			'nums'=>'730',
			'miaoshu'=>'司法笑话,司法,法律笑话,sifaxiaohua,falvxiaohua,sifa'
			),
	14=>array('name'=>'宗教笑话',
			'type'=>'1',
			'nums'=>'765',
			'miaoshu'=>'宗教笑话,宗教,宗教类,zongjiaoxiaohua,zongjiao'
			),
	36=>array('name'=>'食物水果',
			'type'=>'2',
			'nums'=>'7',
			'miaoshu'=>'食物水果,食物搞笑图,水果搞笑图,食物,水果,shiwu,shuiguo,shuwugaoxiao,shuiguogaoxiao'
			),
	37=>array('name'=>'浪漫爱情',
			'type'=>'2',
			'nums'=>'11',
			'miaoshu'=>'浪漫爱情,浪漫,爱情,浪漫图片,爱情图片,美丽爱情,lanman,aiqing,lanmanaiqing,lanmantupian,aiqingtupian'
			),
	38=>array('name'=>'交通事故',
			'type'=>'2',
			'nums'=>'22',
			'miaoshu'=>'交通事故,交通事故图片,搞笑交通事故图片,jiaotongshigu,jiaotongshigutupian,gaoxiaojiaotongshigu'
			),
	39=>array('name'=>'风景图片',
			'type'=>'2',
			'nums'=>'17',
			'miaoshu'=>'风景图片,风景奇观,风景,奇观,风景图片,奇观图片,fengjing,qiguan,fengjingtupian,qiguantupian'
			),
	40=>array('name'=>'摄影作品',
			'type'=>'2',
			'nums'=>'2',
			'miaoshu'=>'摄影作品,摄影照片,搞笑摄影,sheyingzuopin,gaoxiaosheying,sheying'
			),
	41=>array('name'=>'动物图片',
			'type'=>'2',
			'nums'=>'4',
			'miaoshu'=>'动物图片,动物世界,动物图片,动物搞笑图片,dongwushijie,dongwutupian,gaoxiaodongwu'
			),
	35=>array('name'=>'搞笑儿童',
			'type'=>'2',
			'nums'=>'37',
			'miaoshu'=>'搞笑儿童,儿童搞笑,儿童搞笑图,可爱儿童,gaoxiaoertong,ertonggaoxiao,keaiertong'
			),
	34=>array('name'=>'动物搞笑',
			'type'=>'2',
			'nums'=>'49',
			'miaoshu'=>'动物搞笑,搞笑动物图片,可爱动物图片,dongwu,dongwutupian,dongwugaoxiao'
			),
	33=>array('name'=>'动漫美女',
			'type'=>'2',
			'nums'=>'40',
			'miaoshu'=>'动漫美女,漫画图片,漫画,搞笑漫画,manhua,gaoxiaomanhua,manhuatupian'
			),
	32=>array('name'=>'主流唯美',
			'type'=>'2',
			'nums'=>'6',
			'miaoshu'=>'主流唯美,主流唯美图片,唯美图片,weimeitupian,zhuliutupian'
			),
	31=>array('name'=>'动态图片',
			'type'=>'2',
			'nums'=>'61',
			'miaoshu'=>'动态图片,可以动的图片,动态搞笑图片,动画图片,dongtaitupian,donghuo,daitiangaoxiao'
			),
	30=>array('name'=>'性感美女',
			'type'=>'2',
			'nums'=>'70',
			'miaoshu'=>'性感美女,漂亮美女,美女,性感,诱人美女,美女图片,高清美女,meinv,xingganmeinv,xinggan,youhuo,gaoxing'
			),
	29=>array('name'=>'恶搞图片',
			'type'=>'2',
			'nums'=>'282',
			'miaoshu'=>'恶搞图片,超级恶搞,超级恶搞图片,恶搞图片,无语的图片,egaotupian,chaojiegaotupian,wuyutupian'
			),
	28=>array('name'=>'搞笑图片',
			'type'=>'2',
			'nums'=>'286',
			'miaoshu'=>'很搞笑的图片,笑死人的图片,gaoxiaotupian,xiaohuatupian,搞笑图片,笑图'
			),
	42=>array('name'=>'创意图片',
			'type'=>'2',
			'nums'=>'0',
			'miaoshu'=>'创意图片,创意,图片,想像图片,chuangyi,chuangyitupian,xiangxiangtu'
			),
	);
?>